		// Add Firebase config here to enable shared data across devices.
		const FIREBASE_CONFIG = {       apiKey: "AIzaSyD3U8k3n8lo4mDRRVm4FW6o0uTQjwnGllE",
										authDomain: "gastos-89421.firebaseapp.com",
										databaseURL: "https://gastos-89421-default-rtdb.firebaseio.com",
										projectId: "gastos-89421",
										storageBucket: "gastos-89421.firebasestorage.app",
										appId: "1:556270144789:web:3b7522c075b36cdca5ad1c",
										messagingSenderId: "556270144789",
										measurementId: "G-NWNZDZVV6G"};
		const sharedRoomParam = new URLSearchParams(location.search).get('hogar');
		const sharedRoom = sharedRoomParam || 'mi-hogar';
		let workspaceMode = sharedRoomParam?'shared':(localStorage.getItem('saldo-workspace-mode') || 'shared');
		let cloudDatabase = null;
		let cloudSyncStarted = false;
		const initialExpenses = [
			{id:'1',name:'Compra semanal',amount:86.40,category:'Alimentación',date:'2026-08-21',person:'María',icon:'shopping-basket'},
			{id:'2',name:'Gasolina',amount:52.00,category:'Transporte',date:'2026-08-20',person:'Javier',icon:'fuel'},
			{id:'3',name:'Luz y agua',amount:118.75,category:'Hogar',date:'2026-08-19',person:'María',icon:'house'},
			{id:'4',name:'Cine y cena',amount:42.50,category:'Ocio',date:'2026-08-18',person:'Javier',icon:'clapperboard'}
		];
		const categoryIcons = { Alimentación:'shopping-basket', Transporte:'car-front', Hogar:'house', Ocio:'clapperboard', Salud:'heart-pulse', Otros:'circle-dot' };
		let expenses = [];
		let incomes = [];
		let activeUser = JSON.parse(localStorage.getItem('saldo-session') || 'null');
		let authMode = 'login';
		let editingId = null;
		const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
		const today = () => new Date().toISOString().slice(0,10);
		const monthKey = () => today().slice(0,7);
		const formatDate = value => new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short'}).format(new Date(value+'T12:00:00')).replace('.','');
		const userKey = email => encodeURIComponent(email.toLowerCase().trim());
		async function hashPassword(password){ const bytes=new TextEncoder().encode(password); const digest=await crypto.subtle.digest('SHA-256',bytes); return Array.from(new Uint8Array(digest)).map(byte=>byte.toString(16).padStart(2,'0')).join(''); }
		function loadUserData(user, firstLogin=false){ if(!user){clearCurrentData();return;} const key=(workspaceMode==='shared'?'saldo-user-data-':'saldo-personal-data-')+userKey(user.email); const stored=JSON.parse(localStorage.getItem(key)||'null'); if(stored){expenses=stored.expenses||[];incomes=stored.incomes||[];}else{expenses=[];incomes=[];if(firstLogin)localStorage.setItem(key,JSON.stringify({expenses,incomes}));} }
		function clearCurrentData(){ expenses=[];incomes=[];document.getElementById('dateFilter').value='';document.getElementById('allDateFilter').value='';document.getElementById('monthlyCategoryFilter').value='all';render(); }
		function updateWorkspaceMode(){ const shared=workspaceMode==='shared';document.getElementById('workspaceMode').textContent=shared?'Hogar compartido · '+sharedRoom:'Modo individual';document.getElementById('shareBtnLabel').textContent=shared?'Salir del hogar':'Compartir hogar';document.getElementById('syncLabel').textContent=shared?'Sala '+sharedRoom:'Solo este dispositivo';updateToggleModeBtn(); }
		function updateToggleModeBtn(){ const btn=document.getElementById('toggleModeBtn');const shared=workspaceMode==='shared';btn.title=shared?'Desconectar del hogar':'Conectar a hogar';btn.classList.toggle('active',shared);btn.style.borderColor=shared?'#79a98a':'var(--line)';btn.style.color=shared?'var(--green)':'var(--muted)';lucide.createIcons(); }
		function leaveSharedRoom(){ if(workspaceMode!=='shared'){openShare();return;}if(!confirm('¿Salir del hogar compartido? Tus datos del hogar se conservarán en la sala, pero esta cuenta pasará a modo individual.'))return;workspaceMode='individual';localStorage.setItem('saldo-workspace-mode','individual');if(cloudDatabase&&cloudSyncStarted){cloudDatabase.ref('saldo-hogares/'+sharedRoom+'/expenses').off();cloudDatabase.ref('saldo-hogares/'+sharedRoom+'/incomes').off();cloudSyncStarted=false;}clearCurrentData();loadUserData(activeUser);updateWorkspaceMode();toast('Ahora estás en modo individual');}
		function cloudList(value){ if(Array.isArray(value))return value; if(value&&typeof value==='object')return Object.keys(value).sort((a,b)=>Number(a)-Number(b)).map(key=>value[key]); return []; }
		function save(){ localStorage.setItem('saldo-expenses',JSON.stringify(expenses)); localStorage.setItem('saldo-incomes',JSON.stringify(incomes)); if(activeUser){const key=(workspaceMode==='shared'?'saldo-user-data-':'saldo-personal-data-')+userKey(activeUser.email);localStorage.setItem(key,JSON.stringify({expenses,incomes}));} if(workspaceMode==='shared'&&cloudDatabase){ cloudDatabase.ref('saldo-hogares/'+sharedRoom+'/expenses').set(expenses);cloudDatabase.ref('saldo-hogares/'+sharedRoom+'/incomes').set(incomes); } }
		async function restoreCloudData(){ if(!cloudDatabase||!activeUser)return; const [expenseSnapshot,incomeSnapshot]=await Promise.all([cloudDatabase.ref('saldo-hogares/'+sharedRoom+'/expenses').once('value'),cloudDatabase.ref('saldo-hogares/'+sharedRoom+'/incomes').once('value')]); expenses=cloudList(expenseSnapshot.val());incomes=cloudList(incomeSnapshot.val());localStorage.setItem('saldo-user-data-'+userKey(activeUser.email),JSON.stringify({expenses,incomes}));render(); }
		function render(){
			const currentMonth = expenses.filter(x=>x.date.startsWith(monthKey())); const total=currentMonth.reduce((s,x)=>s+x.amount,0); const todayTotal=expenses.filter(x=>x.date===today()).reduce((s,x)=>s+x.amount,0); const activeDays=new Set(currentMonth.map(x=>x.date)).size; const incomeTotal=incomes.filter(x=>x.date.startsWith(monthKey())).reduce((s,x)=>s+x.amount,0);
			document.getElementById('monthTotal').textContent=money(total); document.getElementById('monthCount').textContent=currentMonth.length+' gastos'; document.getElementById('dailyAverage').textContent=money(activeDays?total/activeDays:0); document.getElementById('todayTotal').textContent=money(todayTotal);
			document.getElementById('incomeSummaryTotal').textContent=money(incomeTotal); document.getElementById('incomeSummaryBalance').textContent=money(incomeTotal-total);
			const accumulatedExpenses=expenses.filter(x=>x.date.slice(0,7)<=monthKey()).reduce((sum,x)=>sum+x.amount,0); const accumulatedIncome=incomes.filter(x=>x.date.slice(0,7)<=monthKey()).reduce((sum,x)=>sum+x.amount,0); const balance=accumulatedIncome-accumulatedExpenses; const availablePercent=accumulatedIncome>0?Math.round((balance/accumulatedIncome)*100):0; document.getElementById('budgetPercent').textContent=Math.max(0,availablePercent)+'% acumulado'; document.getElementById('budgetValue').textContent=money(balance);
			renderChart(); renderCategories(currentMonth,total); renderTransactions(); renderMonthly(); renderIncomeTransactions(); lucide.createIcons();
		}
		function renderChart(){ const days=Number(document.getElementById('chartPeriod').value); const values=[]; for(let i=days-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);values.push({key,label:days===7?new Intl.DateTimeFormat('es-ES',{weekday:'short'}).format(d).slice(0,2):d.getDate(),value:expenses.filter(x=>x.date===key).reduce((s,x)=>s+x.amount,0)});} const max=Math.max(...values.map(x=>x.value),100); document.getElementById('chart').innerHTML=values.map((x,i)=>`<div class="bar-wrap"><div class="bar ${i===values.length-1?'current':''}" style="height:${Math.max(5,x.value/max*100)}%" title="${money(x.value)}"></div><div class="bar-label">${x.label}</div></div>`).join(''); }
		function renderCategories(items,total){ const grouped={}; items.forEach(x=>grouped[x.category]=(grouped[x.category]||0)+x.amount); const rows=Object.entries(grouped).sort((a,b)=>b[1]-a[1]); document.getElementById('categories').innerHTML=rows.length?rows.slice(0,5).map(([name,value])=>`<div class="category-row"><div class="cat-icon"><i data-lucide="${categoryIcons[name]}"></i></div><div><div class="cat-name">${name}</div><div class="progress"><i style="width:${Math.max(3,value/total*100)}%"></i></div></div><div class="cat-total">${money(value)}</div></div>`).join(''):'<div class="empty">Aún no hay gastos este mes.</div>'; }
		function expenseMarkup(list){ return list.length?list.map(x=>`<div class="transaction"><div class="tx-icon"><i data-lucide="${categoryIcons[x.category]||'circle-dot'}"></i></div><div><div class="tx-name">${x.name}</div><div class="tx-cat">${x.category} · ${formatDate(x.date)} · ${x.person||'Usuario'}</div></div><div class="tx-amount">${money(x.amount)}</div><div class="expense-actions"><button class="expense-action" data-expense-edit="${x.id}" title="Editar gasto"><i data-lucide="pencil"></i></button><button class="expense-action delete" data-expense-delete="${x.id}" title="Eliminar gasto"><i data-lucide="trash-2"></i></button></div></div>`).join(''):'<div class="empty">No hay movimientos para este filtro.</div>'; }
		function renderTransactions(){ const filter=document.getElementById('dateFilter').value; const list=expenses.filter(x=>!filter||x.date===filter).sort((a,b)=>b.date.localeCompare(a.date)); document.getElementById('transactions').innerHTML=expenseMarkup(list); lucide.createIcons(); }
		function transactionMarkup(list){ return expenseMarkup(list); }
		function renderAllTransactions(){ const filter=document.getElementById('allDateFilter').value; const list=expenses.filter(x=>!filter||x.date===filter).sort((a,b)=>b.date.localeCompare(a.date)); document.getElementById('movementCount').textContent=list.length+' movimientos encontrados'; document.getElementById('allTransactions').innerHTML=transactionMarkup(list); lucide.createIcons(); }
		function renderIncomeTransactions(){ const list=incomes.filter(x=>x.date.startsWith(monthKey())).sort((a,b)=>b.date.localeCompare(a.date)); document.getElementById('incomeTransactions').innerHTML=list.length?list.map(x=>`<div class="transaction"><div class="tx-icon" style="background:#eaf4ed;color:var(--green)"><i data-lucide="arrow-down-to-line"></i></div><div><div class="tx-name">${x.name}</div><div class="tx-cat">Ingreso · ${formatDate(x.date)} · ${x.person}</div></div><div class="tx-amount" style="color:var(--green)">+${money(x.amount)}</div><div class="income-actions"><button class="income-action" data-income-edit="${x.id}" title="Editar ingreso"><i data-lucide="pencil"></i></button><button class="income-action delete" data-income-delete="${x.id}" title="Eliminar ingreso"><i data-lucide="trash-2"></i></button></div></div>`).join(''):'<div class="empty">Aún no hay ingresos registrados.</div>'; lucide.createIcons(); }
		function renderMonthly(){ const currentMonth=expenses.filter(x=>x.date.startsWith(monthKey())); const category=document.getElementById('monthlyCategoryFilter').value; const filtered=category==='all'?currentMonth:currentMonth.filter(x=>x.category===category); const total=filtered.reduce((sum,x)=>sum+x.amount,0); const monthIncome=incomes.filter(x=>x.date.startsWith(monthKey())); const incomeTotal=monthIncome.reduce((sum,x)=>sum+x.amount,0); const byDay={}; const byCategory={}; filtered.forEach(x=>{byDay[x.date]=(byDay[x.date]||0)+x.amount;byCategory[x.category]=(byCategory[x.category]||0)+x.amount;}); const peak=Object.entries(byDay).sort((a,b)=>b[1]-a[1])[0]; const top=Object.entries(byCategory).sort((a,b)=>b[1]-a[1])[0]; document.getElementById('monthlyTitle').textContent=new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(new Date()).replace(/^./,letter=>letter.toUpperCase()); document.getElementById('monthlyTotal').textContent=money(total); document.getElementById('monthlyExpensesCount').textContent=filtered.length+' movimientos'; document.getElementById('monthlyPeak').textContent=money(peak?.[1]||0); document.getElementById('monthlyPeakDate').textContent=peak?formatDate(peak[0]):'Sin actividad'; document.getElementById('monthlyTopCategory').textContent=top?.[0]||'-'; document.getElementById('monthlyBreakdown').innerHTML=Object.entries(byCategory).sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<tr><td><strong>${name}</strong></td><td>${filtered.filter(x=>x.category===name).length}</td><td>${money(value)} <span class="cat-meta">(${total?Math.round(value/total*100):0}%)</span></td></tr>`).join('')||'<tr><td colspan="3" class="empty">No hay gastos este mes.</td></tr>'; document.getElementById('monthlyIncomeTotal').textContent=money(incomeTotal);document.getElementById('monthlyIncomeBalance').textContent='Balance disponible: '+money(incomeTotal-total);document.getElementById('incomeTransactions').innerHTML=monthIncome.length?monthIncome.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="transaction"><div class="tx-icon" style="background:#eaf4ed;color:var(--green)"><i data-lucide="arrow-down-to-line"></i></div><div><div class="tx-name">${x.name}</div><div class="tx-cat">Ingreso · ${formatDate(x.date)} · ${x.person}</div></div><div class="tx-amount" style="color:var(--green)">+${money(x.amount)}</div><div class="income-actions"><button class="income-action" data-income-edit="${x.id}" title="Editar ingreso"><i data-lucide="pencil"></i></button><button class="income-action delete" data-income-delete="${x.id}" title="Eliminar ingreso"><i data-lucide="trash-2"></i></button></div></div>`).join(''):'<div class="empty">Aún no hay ingresos registrados.</div>'; lucide.createIcons(); }
		function openModal(id){ editingId=id||null; const item=expenses.find(x=>x.id===id); document.getElementById('modalTitle').textContent=id?'Editar gasto':'Añadir gasto'; document.getElementById('expenseName').value=item?.name||'';document.getElementById('expenseAmount').value=item?.amount||'';document.getElementById('expenseCategory').value=item?.category||'Alimentación';document.getElementById('expenseDate').value=item?.date||today();document.getElementById('modalBackdrop').classList.add('show'); setTimeout(()=>document.getElementById('expenseName').focus(),50); }
		function closeModal(){document.getElementById('modalBackdrop').classList.remove('show');document.getElementById('expenseForm').reset();editingId=null;}
		let editingIncomeId=null;
		function openIncomeModal(id){ editingIncomeId=id||null; const item=incomes.find(x=>x.id===id); document.getElementById('incomeDate').value=item?.date||today();document.getElementById('incomeName').value=item?.name||'';document.getElementById('incomeAmount').value=item?.amount||'';document.querySelector('#incomeModalBackdrop h2').textContent=id?'Editar ingreso':'Añadir ingreso';document.getElementById('incomeModalBackdrop').classList.add('show');setTimeout(()=>document.getElementById('incomeName').focus(),50); }
		function closeIncomeModal(){document.getElementById('incomeModalBackdrop').classList.remove('show');document.getElementById('incomeForm').reset();editingIncomeId=null;document.querySelector('#incomeModalBackdrop h2').textContent='Añadir ingreso';}
		function openShare(){ workspaceMode='shared';localStorage.setItem('saldo-workspace-mode','shared');if(activeUser)loadUserData(activeUser);updateWorkspaceMode();render();const link=new URL(location.href);link.searchParams.set('hogar',sharedRoom);document.getElementById('shareRoomCode').textContent=sharedRoom;document.getElementById('shareLink').value=link.href;document.getElementById('shareBackdrop').classList.add('show');lucide.createIcons();if(!cloudDatabase)startCloudSync(); }
		function closeShare(){document.getElementById('shareBackdrop').classList.remove('show');}
		function openAuth(){authMode='login';document.getElementById('authBackdrop').classList.add('show');updateAuthMode();updateAuthNameField();setTimeout(()=>document.getElementById('authEmail').focus(),50);}
		function closeAuth(){document.getElementById('authBackdrop').classList.remove('show');document.getElementById('authForm').reset();updateAuthNameField();}
		function updateAuthMode(){const creating=authMode==='signup';document.getElementById('authTitle').textContent=creating?'Crear cuenta':'Iniciar sesión';document.getElementById('authCopy').textContent=creating?'Regístrate para usar tu hogar compartido desde cualquier dispositivo.':'Accede a tu hogar compartido para consultar y registrar gastos desde cualquier dispositivo.';document.getElementById('authSubmit').textContent=creating?'Crear cuenta':'Entrar';document.getElementById('forgotPassword').style.display=creating?'none':'block';document.getElementById('authSwitch').innerHTML=creating?'¿Ya tienes cuenta? <strong>Iniciar sesión</strong>':'¿No tienes cuenta? <strong>Crear cuenta</strong>';}
		function updateAuthNameField(){ const email=document.getElementById('authEmail').value.trim().toLowerCase(); const users=JSON.parse(localStorage.getItem('saldo-users')||'{}'); const knownUser=users[email]; const field=document.getElementById('authNameField'); const input=document.getElementById('authName'); field.style.display=authMode==='signup'||!knownUser?'grid':'none'; input.required=authMode==='signup'||!knownUser; input.value=authMode==='signup'?'':knownUser?.name||''; }
		function getTimeGreeting(){ const hour=new Date().getHours(); if(hour<12)return 'Buenos días'; if(hour<18)return 'Buenas tardes'; return 'Buenas noches'; }
		function updateSessionButton(){ const session=JSON.parse(localStorage.getItem('saldo-session')||'null'); const name=session?.name||'María'; const button=document.getElementById('loginBtn'); button.textContent=session?'Cerrar sesión':'Iniciar sesión'; button.title=session?session.email:''; const greetingEl=document.getElementById('welcomeGreeting'); if(greetingEl) greetingEl.textContent=getTimeGreeting(); if(session){document.getElementById('welcomeName').textContent=name;document.querySelector('.user-name').textContent=name;document.querySelectorAll('[data-user-avatar]').forEach(avatar=>avatar.textContent=name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase());} }
		function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}
		document.getElementById('todayLabel').textContent=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
		document.getElementById('addBtn').onclick=()=>openModal();document.getElementById('addIncomeBtn').onclick=()=>openIncomeModal();document.getElementById('closeModal').onclick=closeModal;document.getElementById('cancelModal').onclick=closeModal;document.getElementById('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};document.getElementById('closeIncomeModal').onclick=closeIncomeModal;document.getElementById('cancelIncomeModal').onclick=closeIncomeModal;document.getElementById('incomeModalBackdrop').onclick=e=>{if(e.target.id==='incomeModalBackdrop')closeIncomeModal()};
		document.getElementById('expenseForm').onsubmit=e=>{e.preventDefault();const data={id:editingId||Date.now().toString(),name:document.getElementById('expenseName').value.trim(),amount:Number(document.getElementById('expenseAmount').value),category:document.getElementById('expenseCategory').value,date:document.getElementById('expenseDate').value,person:activeUser?.name||'Usuario'};expenses=editingId?expenses.map(x=>x.id===editingId?{...x,...data}:x):[data,...expenses];save();closeModal();render();toast(editingId?'Gasto actualizado':'Gasto guardado correctamente');};
		document.getElementById('incomeForm').onsubmit=e=>{e.preventDefault();const session=JSON.parse(localStorage.getItem('saldo-session')||'null');const data={id:editingIncomeId||Date.now().toString(),name:document.getElementById('incomeName').value.trim(),amount:Number(document.getElementById('incomeAmount').value),date:document.getElementById('incomeDate').value,person:session?.name||'Usuario'};incomes=editingIncomeId?incomes.map(x=>x.id===editingIncomeId?{...x,...data}:x):[data,...incomes];save();closeIncomeModal();render();toast(editingIncomeId?'Ingreso actualizado correctamente':'Ingreso guardado correctamente');};
		document.getElementById('incomeTransactions').addEventListener('click',event=>{const editButton=event.target.closest('[data-income-edit]');const deleteButton=event.target.closest('[data-income-delete]');if(editButton){openIncomeModal(editButton.dataset.incomeEdit);}if(deleteButton){const item=incomes.find(x=>x.id===deleteButton.dataset.incomeDelete);if(item&&confirm('¿Eliminar el ingreso "'+item.name+'"?')){incomes=incomes.filter(x=>x.id!==item.id);save();render();toast('Ingreso eliminado');}}});
		document.querySelectorAll('#transactions,#allTransactions').forEach(list=>list.addEventListener('click',event=>{const editButton=event.target.closest('[data-expense-edit]');const deleteButton=event.target.closest('[data-expense-delete]');if(editButton){openModal(editButton.dataset.expenseEdit);}if(deleteButton){const item=expenses.find(x=>x.id===deleteButton.dataset.expenseDelete);if(item&&confirm('¿Eliminar el gasto "'+item.name+'"?')){expenses=expenses.filter(x=>x.id!==item.id);save();render();toast('Gasto eliminado');}}}));
		document.getElementById('manageIncomeBtn').onclick=()=>{document.querySelector('[data-view="monthly"]').click();setTimeout(()=>document.getElementById('incomeTransactions').scrollIntoView({behavior:'smooth',block:'center'}),50);};
		document.getElementById('dateFilter').onchange=renderTransactions;document.getElementById('clearFilter').onclick=()=>{document.getElementById('dateFilter').value='';renderTransactions()};document.getElementById('chartPeriod').onchange=renderChart;document.getElementById('allDateFilter').onchange=renderAllTransactions;document.getElementById('clearAllFilter').onclick=()=>{document.getElementById('allDateFilter').value='';renderAllTransactions()};document.getElementById('monthlyCategoryFilter').onchange=renderMonthly;document.getElementById('addBtnMovements').onclick=()=>openModal();
		document.getElementById('loginBtn').onclick=async()=>{ if(localStorage.getItem('saldo-session')){if(!confirm('¿Deseas cerrar tu sesión?'))return;if(FIREBASE_CONFIG.apiKey&&window.firebase&&firebase.apps.length)await firebase.auth().signOut();localStorage.removeItem('saldo-session');activeUser=null;clearCurrentData();updateSessionButton();toast('Sesión cerrada');return;} openAuth(); }; document.getElementById('closeAuth').onclick=closeAuth;document.getElementById('cancelAuth').onclick=closeAuth;document.getElementById('authBackdrop').onclick=e=>{if(e.target.id==='authBackdrop')closeAuth()};document.getElementById('authEmail').oninput=updateAuthNameField;
		document.getElementById('authSwitch').onclick=()=>{authMode=authMode==='login'?'signup':'login';updateAuthMode();updateAuthNameField();};
		document.getElementById('shareBtn').onclick=leaveSharedRoom;document.getElementById('shareBtnTop').onclick=openShare;document.getElementById('toggleModeBtn').onclick=()=>{if(workspaceMode==='shared'){if(!confirm('¿Desconectar del hogar compartido? Tus datos se conservarán pero pasarás a modo individual.'))return;leaveSharedRoom();}else{openShare();}updateToggleModeBtn();};document.getElementById('closeShare').onclick=closeShare;document.getElementById('shareBackdrop').onclick=e=>{if(e.target.id==='shareBackdrop')closeShare()};document.getElementById('copyShare').onclick=async()=>{const link=document.getElementById('shareLink').value;try{await navigator.clipboard.writeText(link);}catch(error){document.getElementById('shareLink').select();document.execCommand('copy');}toast('Enlace copiado');};document.getElementById('nativeShare').onclick=async()=>{const link=document.getElementById('shareLink').value;if(navigator.share){await navigator.share({title:'Mi hogar en Saldo',text:'Únete a mi sala de gastos compartidos',url:link});}else{document.getElementById('shareLink').select();document.execCommand('copy');toast('Enlace copiado');}};
		document.getElementById('authForm').onsubmit=async e=>{ e.preventDefault(); const typedName=document.getElementById('authName').value.trim(); const email=document.getElementById('authEmail').value.trim().toLowerCase(); const password=document.getElementById('authPassword').value; const users=JSON.parse(localStorage.getItem('saldo-users')||'{}'); const knownUser=users[email]; let name=knownUser?.name||typedName; if((authMode==='signup'&&name.length<2)||password.length<6){toast(authMode==='signup'?'Escribe tu nombre y una contraseña de al menos 6 caracteres.':'Escribe una contraseña de al menos 6 caracteres.');return;} try{ let firstLogin=false; if(FIREBASE_CONFIG.apiKey&&window.firebase){ if(!firebase.apps.length)firebase.initializeApp(FIREBASE_CONFIG); let credential; if(authMode==='signup'){credential=await firebase.auth().createUserWithEmailAndPassword(email,password);}else{credential=await firebase.auth().signInWithEmailAndPassword(email,password);} name=name||credential.user.displayName||email.split('@')[0]; if(!credential.user.displayName&&name)await credential.user.updateProfile({displayName:name}); }else{ const passwordHash=await hashPassword(password); if(authMode==='login'&&knownUser&&knownUser.passwordHash!==passwordHash){toast('Correo o contraseña incorrectos.');return;} firstLogin=!knownUser; users[email]={name,email,passwordHash}; localStorage.setItem('saldo-users',JSON.stringify(users)); } activeUser={name,email};localStorage.setItem('saldo-session',JSON.stringify(activeUser));loadUserData(activeUser,firstLogin);if(!firstLogin||!FIREBASE_CONFIG.apiKey)save();if(FIREBASE_CONFIG.apiKey)await restoreCloudData();closeAuth();updateSessionButton();render();toast(authMode==='signup'?'Cuenta creada correctamente.':'Sesión iniciada correctamente'); }catch(error){toast(error.code==='auth/email-already-in-use'?'Ese correo ya está registrado.':'No se pudo validar la cuenta. Revisa tus datos.');} };
		document.getElementById('forgotPassword').onclick=async()=>{ const email=document.getElementById('authEmail').value.trim().toLowerCase(); if(!email){toast('Escribe tu correo electrónico primero.');return;} try{ if(FIREBASE_CONFIG.apiKey&&window.firebase){if(!firebase.apps.length)firebase.initializeApp(FIREBASE_CONFIG);await firebase.auth().sendPasswordResetEmail(email);toast('Te enviamos un enlace para recuperar tu contraseña.');}else{const users=JSON.parse(localStorage.getItem('saldo-users')||'{}');toast(users[email]?'En modo local, vuelve a iniciar sesión con tu cuenta registrada.':'No existe una cuenta local con ese correo.');} }catch(error){toast('No se pudo enviar el enlace de recuperación.');} };
		document.getElementById('notifyBtn').onclick=()=>toast('No tienes notificaciones nuevas'); document.getElementById('settingsBtn').onclick=()=>toast(FIREBASE_CONFIG.apiKey?'Sincronización conectada':'Añade tu configuración Firebase para compartir datos');
		document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item[data-view]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.view+'View').classList.add('active');if(btn.dataset.view==='transactions')renderAllTransactions();if(btn.dataset.view==='monthly'){renderMonthly();renderIncomeTransactions();}});
		function attachCloudListeners(){
			if(!cloudDatabase||cloudSyncStarted)return;
			cloudSyncStarted=true;
			cloudDatabase.ref('saldo-hogares/'+sharedRoom+'/expenses').on('value',snapshot=>{ const remote=cloudList(snapshot.val()); if(workspaceMode==='shared'&&(activeUser||firebase.auth().currentUser)){expenses=remote;localStorage.setItem('saldo-expenses',JSON.stringify(expenses));render();} },error=>{document.getElementById('syncLabel').textContent='Error de sincronización';toast('Firebase no puede leer gastos. Revisa las reglas de Database.');});
			cloudDatabase.ref('saldo-hogares/'+sharedRoom+'/incomes').on('value',snapshot=>{ const remote=cloudList(snapshot.val()); if(workspaceMode==='shared'&&(activeUser||firebase.auth().currentUser)){incomes=remote;localStorage.setItem('saldo-incomes',JSON.stringify(incomes));render();} },error=>{document.getElementById('syncLabel').textContent='Error de sincronización';toast('Firebase no puede leer ingresos. Revisa las reglas de Database.');});
			document.getElementById('syncLabel').textContent='Sala '+sharedRoom;
		}
		async function startCloudSync(){
			if(workspaceMode!=='shared'||!FIREBASE_CONFIG.apiKey || !window.firebase) return;
			try{
				if(!firebase.apps.length) firebase.initializeApp(FIREBASE_CONFIG);
				cloudDatabase=firebase.database();
				firebase.auth().onAuthStateChanged(user=>{ if(user){ attachCloudListeners();restoreCloudData(); } });
			}catch(error){ document.getElementById('syncLabel').textContent='Modo local'; }
		}
		if(FIREBASE_CONFIG.apiKey) document.getElementById('syncLabel').textContent='Conectando...';
		updateWorkspaceMode();
		if(activeUser)loadUserData(activeUser);
		updateSessionButton();
		render();
		startCloudSync();
	